apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: symfony-crud-api
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        run.googleapis.com/client-name: "github-actions"
    spec:
      containers:
        - image: ${AG_DOCKER_USERNAME}/symfony-crud-api:${VERSION}
          ports:
            - containerPort: 80
          env:
            - name: APP_ENV
              value: "prod"
            - name: DB_NAME
              value: "api_db"
            - name: LOKI_URL
              value: "35.240.99.88:3100"
            - name: INSTANCE_NAME
              value: "${INSTANCE_NAME}"
          resources:
            limits:
              memory: "512Mi"
  traffic:
    - percent: 100
      latestRevision: true